name: flutter_google_places_sdk_platform_interface
description: A common platform interface for accessing google maps native sdk on various platforms
version: 0.2.4+3
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_platform_interface

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  mockito: ^5.3.2

flutter:
  assets:
    - assets/google/
