name: flutter_google_places_sdk_platform_interface
description: A common platform interface for accessing google maps native sdk on various platforms
version: 0.2.6
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_platform_interface

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.3.2

flutter:
  assets:
    - assets/google/
