name: flutter_google_places_sdk_web
description: The web implementation of Flutter plugin for google places sdk
version: 0.1.4
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_web

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.2.5
  js: ^0.6.7
  google_maps: ^6.3.0
  collection: ^1.17.2 # Can't upgrade to 1.18 due to flutter sdk version

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
  plugin:
    platforms:
      web:
        fileName: flutter_google_places_sdk_web.dart
        pluginClass: FlutterGooglePlacesSdkWebPlugin
