name: flutter_google_places_sdk_web
description: The web implementation of Flutter plugin for google places sdk
version: 0.2.0
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_web

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.3.2+1
  google_maps: ^8.2.0
  # Can't upgrade to 1.18 due to flutter sdk version
  collection: ^1.19.1
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1

flutter:
  plugin:
    platforms:
      web:
        fileName: flutter_google_places_sdk_web.dart
        pluginClass: FlutterGooglePlacesSdkWebPlugin
