name: flutter_google_places_sdk_macos
description: The macos implementation of Flutter plugin for google places sdk
version: 0.3.0
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_macos

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.4.0
  flutter_google_places_sdk_http: ^0.3.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: flutter_google_places_sdk
    platforms:
      macos:
        fileName: flutter_google_places_sdk_macos.dart
        dartPluginClass: FlutterGooglePlacesSdkMacosPlugin
