name: flutter_google_places_sdk_linux
description: The linux implementation of Flutter plugin for google places sdk
version: 0.1.1
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_linux

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.2.4+3
  flutter_google_places_sdk_http: ^0.1.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: flutter_google_places_sdk
    platforms:
      linux:
        fileName: flutter_google_places_sdk_linux.dart
        dartPluginClass: FlutterGooglePlacesSdkLinuxPlugin
