name: flutter_google_places_sdk_linux
description: The linux implementation of Flutter plugin for google places sdk
version: 0.1.4
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_linux

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.3.1+1
  flutter_google_places_sdk_http: # ^0.1.4
    path: ../flutter_google_places_sdk_http

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: flutter_google_places_sdk
    platforms:
      linux:
        fileName: flutter_google_places_sdk_linux.dart
        dartPluginClass: FlutterGooglePlacesSdkLinuxPlugin
