name: flutter_google_places_sdk_http
description: An http implementation of Flutter plugin to be used by other platform implementation
version: 0.2.1
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_http

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  latlong2: ^0.9.1
  flutter_google_places_sdk_platform_interface: ^0.3.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  mockito: ^5.4.0