name: flutter_google_places_sdk_ios
description: iOS implementation for flutter google places sdk
version: 0.1.0
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_ios

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.11

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftFlutterGooglePlacesSdkPlugin
