name: flutter_google_places_sdk_ios
description: The iOS implementation of Flutter plugin for google places sdk
version: 0.1.2+1
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_ios

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.2.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.11
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftFlutterGooglePlacesSdkIosPlugin
