name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.4.3
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.4.0
  flutter_google_places_sdk_ios: ^0.2.2
  flutter_google_places_sdk_web: ^0.2.2
  flutter_google_places_sdk_android: ^0.3.0
  flutter_google_places_sdk_windows: ^0.3.0
  flutter_google_places_sdk_linux: ^0.2.2
  flutter_google_places_sdk_macos: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_google_places_sdk_android
      ios:
        default_package: flutter_google_places_sdk_ios
      web:
        default_package: flutter_google_places_sdk_web
      windows:
        default_package: flutter_google_places_sdk_windows
      linux:
        default_package: flutter_google_places_sdk_linux
      macos:
        default_package: flutter_google_places_sdk_macos
