name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.3.2+6
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.2.4+3
  flutter_google_places_sdk_ios: ^0.1.2+3
  flutter_google_places_sdk_web: ^0.1.3+3
  flutter_google_places_sdk_android: ^0.1.2+5
  flutter_google_places_sdk_windows: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_google_places_sdk_android
      ios:
        default_package: flutter_google_places_sdk_ios
      web:
        default_package: flutter_google_places_sdk_web
      windows:
        default_package: flutter_google_places_sdk_windows
