name: flutter_google_places_sdk_example
description: Demonstrates how to use the flutter_google_places_sdk plugin.

publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk:
    path: ../../flutter_google_places_sdk

dependency_overrides:
  flutter_google_places_sdk_platform_interface: ^0.4.0
  flutter_google_places_sdk_web: ^0.3.0
  flutter_google_places_sdk_android: ^0.3.0
  flutter_google_places_sdk_windows: ^0.3.0
  flutter_google_places_sdk_linux: ^0.3.0
  flutter_google_places_sdk_macos: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
