name: flutter_google_places_sdk_example
description: Demonstrates how to use the flutter_google_places_sdk plugin.

publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk:
    path: ../../flutter_google_places_sdk

dependency_overrides:
  flutter_google_places_sdk_platform_interface:
    path: ../../flutter_google_places_sdk_platform_interface
  flutter_google_places_sdk_ios:
    path: ../../flutter_google_places_sdk_ios
  flutter_google_places_sdk_web:
    path: ../../flutter_google_places_sdk_web
  flutter_google_places_sdk_android:
    path: ../../flutter_google_places_sdk_android
  flutter_google_places_sdk_windows:
    path: ../../flutter_google_places_sdk_windows
  flutter_google_places_sdk_linux:
    path: ../../flutter_google_places_sdk_linux
  flutter_google_places_sdk_macos:
    path: ../../flutter_google_places_sdk_macos
  flutter_google_places_sdk_http:
    path: ../../flutter_google_places_sdk_http

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
